// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fbhuzjffknymvjnaonpk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZiaHV6amZma255bXZqbmFvbnBrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwODkyMzksImV4cCI6MjA1OTY2NTIzOX0.dhI59mIlZdVYOcV331m2GxMBVLRRVifGxOdEotcRcUg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);